#!/bin/sh
# Syncs repositories and downloads updates, meant to be run as a cronjob.

ping -q -w 1 -c 1 `ip r | grep -m 1 default | cut -d ' ' -f 3` >/dev/null || exit

sudo pacman -Syyuw --noconfirm && polybar-msg hook packages 1

