#!/bin/sh

# If refresh bspwm, remove all previous rules to prevent doubling up
bspc rule -r "*"

###---Autostart---###
killall nm-applet
nm-applet &
xrdb ~/.Xresources &
xrandr --output eDP1 --auto --left-of HDMI2 &
killall sxhkd
sxhkd &
killall picom
picom -b --experimental-backends &
killall dunst
dunst &
killall redshiftgui.elf
redshiftgui &
killall dropbox
dropbox &
killall telegram-desktop
telegram-desktop &
killall discord
discord &
killall brave
brave &
$HOME/.config/polybar/launch.sh &
killall keepassxc
keepassxc &
fcitx-autostart &
mpd &
setwall &

###---MONITORS---###
bspc monitor eDP1 -d 1 2
bspc monitor HDMI2 -d 3 4 5 6 7 8 9 0

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#6b7089"
bspc config active_border_color	"#ada0d3"
bspc config focused_border_color "#91acd1"
bspc config presel_feedback_color	"#95c4ce"
bspc config urgent_border_color "#e98989"

bspc config ignore_ewmh_focus true

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
bspc rule -a Mpv state=fullscreen
bspc rule -a Cherrytree desktop=^1
bspc rule -a Brave-browser desktop=^3
bspc rule -a firefox desktop=^3
bspc rule -a TelegramDesktop desktop=4
bspc rule -a discord desktop=^5
bspc rule -a Zathura state=tiled desktop=^7
bspc rule -a Steam state=tiled desktop=^9
bspc rule -a dota2 desktop=^10
bspc rule -a KeePassXC desktop=^10
bspc rule -a "VirtualBox Manager" desktop=^8
bspc rule -a "Vmware" desktop=^9
